### ISSUE TITLE
Delayed info date format

### ISSUE THREAD

**Issue by alex-shpak** [esl/MongooseIM#415]
Hi.

I'm facing problem with date format coming in `<delay>` and `<x>` in offline messages.

Accoring to [xep-0082](http://xmpp.org/extensions/xep-0082.html) and [xep-0091](http://xmpp.org/extensions/xep-0091.html) date format supposed to be `CCYYMMDDThh:mm:ss[.sss][Z]` But from server I'm getting `2015-04-01T11:29:10.011493Z`

```XML
<message from='***' to='***' xml:lang='' type='chat' id='purplee11a2ccf'>
    <active xmlns='http://jabber.org/protocol/chatstates'/>
    <body>987654321</body>
    <archived by='***' id='A4L80OEHORO1'/>
    <delay xmlns='urn:xmpp:delay' from='***' stamp='2015-04-01T11:29:10.011493Z'>Offline Storage</delay>
    <x xmlns='jabber:x:delay' stamp='20150401T11:29:10.011493'/>
</message>
```

In other places, like usual messages, presences etc I'm getting `2015-04-01T10:42:02Z` in `<delay>` and  `20150401T10:45:38` in `<x>`

Is this behavior correct, or dates should be the same in this blocks?

We are using:
* Mongoose 1.5.0
* psql (PostgreSQL) 9.3.6
* Smack 4.0.6 for client

**Comment by michalwski** [comment]
This was fixed in master branch, relevant PR is #383. Let me know if this patch works for you.

**Comment by alex-shpak** [comment]
Today we tested this patch.
Unfortunately I still getting incorrect date format

```xml
<message from='***' to='***' xml:lang='' type='chat' id='purple9936115b'>
    <active xmlns='http://jabber.org/protocol/chatstates'/>
    <body>okokokok</body>
    <archived by='****' id='A4LUF3E9N2G1'/>
    <delay xmlns='urn:xmpp:delay' from='****' stamp='2015-04-02T14:16:04.406287Z'>Offline Storage</delay>
</message>
```

**Comment by lavrin** [comment]
I've taken a look at [XEP-0082 section 3.2 DateTime](http://xmpp.org/extensions/xep-0082.html#sect-idp285136), specifically example 2 therein, and can't tell what in the `stamp` attribute above does not match the description in the XEP. Could you be more specific?

**Comment by alex-shpak** [comment]
Basically problem is in presented microseconds, they are not match format.
The lowest level according to standard `CCYY-MM-DDThh:mm:ss[.sss]TZD` is optional milliseconds.
Because of that parse utils of Smack library can't parse these dates.

Microseconds is also not mentioned in [Time terms](http://xmpp.org/extensions/xep-0082.html#sect-idp267120) in XEP-0082 as possible characters

**Comment by lavrin** [comment]
Well, sorry, but they are mentioned in the exact table you point at (emphasis added by me):

> sss	fractional second addendum to Time **(MAY contain any number of digits)**

**Comment by lavrin** [comment]
Moreover, without this precise timestamp it's impossible to properly sort archived / offilne messages on the client side. Millisecond precision is often not sufficient for ensuring proper ordering of messages which do not have to be sent in the intended order of display on the endpoint.

**Comment by alex-shpak** [comment]
Yes. I see now. My bad.
Well, I will try to find some solution on client side with parsing microseconds.

**Comment by alex-shpak** [comment]
After some quick research I found that in Smack library they are fixed date parsing with ignoring microseconds.
