### ISSUE TITLE
Old sessions keep in ?SM_BACKEND on resumed session that never will be restored

### ISSUE THREAD

**Issue by artefactop** [esl/MongooseIM#843]
MongooseIM version: 1.6.2
Installed from: source
Erlang/OTP version: 18

When a client resume a session it is not removed from backend https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_c2s.erl#L1488 then if the same client instead restore the session make a new one, the Pid of previous connection doesn't exists so the `replaced` message never arrive https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_sm.erl#L829 and no one delete the entry of previous session

to fix that:

```
              fun({_, Pid} = S) when S /= MaxSID ->
                case process_info(Pid) of
                  undefined -> close_session(S, LUser, LServer, LResource, replaced);
                  _ ->
                    Pid ! replaced
                end;
```

**Comment by bartekgorny** [comment]
I have a problem to reproduce it. I wrote a test whereby a user established a connection, then another connection with the same resource, and the first connection receives "conflict - replaced by a new connection", exactly as it should. Please advice.

**Comment by artefactop** [comment]
Sorry, I forgot to comment, I think the problem is when the new connection goes to different mongooseim node at least in redis backend.

**Comment by bartekgorny** [comment]
Sorry to say that, but I wrote a test for two nodes and ran it with redis backend, and it passed 😕

**Comment by artefactop** [comment]
And old session is replaced/deleted from redis?

**Comment by bartekgorny** [comment]
I ran it with redis, checking user resources and sessions on both nodes, still no result - when user disconnects the backend is clean. This:
https://gist.github.com/bartekgorny/1cf4af3fbc37d9ea4a7107e1708eb3c0
is the test I ran, both on mnesia and redis. And it passes. Anything else I can do to reproduce?

**Comment by artefactop** [comment]
I checked the test and I miss one test case:
- clientA connect to node1
- node1 lose connectivity with clientA and after timeout of stream management it resume the terminate process with `StateData#state.authenticated = resumed`
- clientA connect to node2 (without disconnecting from node1 due a network error)
- now ejabberd_sm:get_user_resources(User, Server) return 2 
- clientA disconnect from node2
- now ejabberd_sm:get_user_resources(User, Server) return 1

**Comment by Jeyhey** [comment]
I have a similar problem but using only one node using MongooseIM 1.5. Every once in a while I have two different entries in mnesia tables 'session' and 'sm_session' for the same user and resource. Is this issue known and was it fixed in a later version?

**Comment by jfjalburquerque** [comment]
It seems that I have the same problem.

Sometimes a user has a permanent session.
It happens when it tries to resume session, it is not deleted and it create a new one.
I can't reproduce it, but it seems the same problem.

**Comment by ludwikbukowski** [comment]
@artefactop 
> node1 lose connectivity with clientA and after timeout of stream management it resume the terminate process with StateData#state.authenticated = resumed

Im not sure if I understand this statement correctly but if the user won't resume the session till the end of the stream management timeout (which is about 600 secs), the process will terminate [1] and the old session will be closed [2]. 
Could you be more precise in this step description?
Thanks!

[1] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_c2s.erl#L1189
[2] https://github.com/esl/MongooseIM/blob/master/apps/ejabberd/src/ejabberd_c2s.erl#L1474

**Comment by Jeyhey** [comment]
I have duplicated sessions again today. Here are the logs:
```
(coco1@localhost)4> mnesia:dirty_read(session,S2).
[{session,{{1474,283302,297387},<0.2740.1>},
          {<<"and1454512183415305">>,
           <<"c.com">>,<<"mobile">>},
          {<<"and1454512183415305">>,
           <<"c.com">>},
          0,
          [{ip,{{178,197,232,144},56505}},
           {conn,c2s_tls},
           {auth_module,ejabberd_auth_internal}]}]
(coco1@localhost)6> mnesia:dirty_read(session,S4).
[{session,{{1474,202504,803204},<0.32682.0>},
          {<<"and1454512183415305">>,
           <<"c.com">>,<<"mobile">>},
          {<<"and1454512183415305">>,
           <<"c.com">>},
          0,
          [{ip,{{178,197,224,98},63844}},
           {conn,c2s_tls},
           {auth_module,ejabberd_auth_internal}]}]
```
I don't exactly know how to reproduce. The android device, on which the app runs, has been switched to flight mode yesterday while connected to MongooseIM. Today flight mode has been switched off and this is where I noticed the duplicated entries.

**Comment by michalwski** [comment]
I believe this was a race condition issue fixed in #1141

**Comment by Jeyhey** [comment]
I back ported the fix to MongooseIM 1.5 and am going to watch if it fixes the problem.

This is by the way a major issue for the following reasons:
  - It happens regularly (especially if the client regularly looses connectivity to the server)
  - Once a multiple entry in the session table happens (I even had 3 entries), messages to offline clients will **never** be delivered. Even if the client reconnects. They are lost forever.
  - And finally, because the multiple entries will never be cleaned up. Only a manual removal or a server restart will clean the table.

Just wanted to point the importance out. I'm very happy that there is a fix now.

**Comment by Jeyhey** [comment]
Unfortunately https://github.com/esl/MongooseIM/pull/1141 does not fix the problem. I spend the evening letting my android app connecting and reconnecting to MongooseIM and found a double entry eventually.

I set log mode to debug and could locate a possible reason. What happens is the following:

1) `wait_for_bind_or_resume` calls `maybe_resume_session`
2) `maybe_resume_session` calls `do_resume_session`
3) `do_resume_session` adds the session to the session table by calling `ejabberd_sm:open_session`
4) then right after `stream_mgmt_handle_ack` is called in `do_resume_session` and returns {stop, _,_}
5) this makes the process call `terminate`
6) `terminate` checks if it should close the session by calling `should_close_session` which returns false because the process is in the state `wait_for_bind_or_resume`
7) the process finishes and the entry in the session table will never be removed

**Comment by michalwski** [comment]
That's super precise @Jeyhey! Thanks for the effort, I'll make sure to write relevant regression test and then a fix.

**Comment by Jeyhey** [comment]
That's great, I'm happy to help.

**Comment by michalwski** [comment]
I've created the test and fix for the issue in this PR #1186

**Comment by michalwski** [comment]
The PR was merged. I'm closing this issue again. Please re-open or submit new if you find more corner cases like this. 

Thanks a lot to everyone involved in this issue. This was very important bug we fixed together!
